### ISSUE TITLE
Open Source Helps!

### ISSUE THREAD

**Issue by WeileiZeng** [goinvo/COVID19#2]
Thanks for your work to help the people in need! Your site has been added! I currently maintain the Open-Source-COVID-19 page, which collects all open source projects related to COVID-19, including maps, data, news, api, analysis, medical and supply information, etc. Please share to anyone who might need the information in the list, or will possibly contribute to some of those projects. You are also welcome to recommend more projects.

https://weileizeng.github.io/Open-Source-COVID-19/

Cheers!

**Comment by WeileiZeng** [comment]
P.S. a minor suggestion
change
understandingcoronavirus.org
in your readme.md to 
https://understandingcoronavirus.org
would give it the magic to link to the website by clicking on it.

**Comment by jen-p** [comment]
Thank you for adding us  and for the feedback! Updated with https://
